version: "3"

services:
  web2lab1-postgres:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - web2lab1-postgres-data:/var/lib/postgresql/data
    networks:
      - web2lab1-network

  web2lab1-backend:
    build:
      context: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - web2lab1-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://web2lab1-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - web2lab1-network

volumes:
  web2lab1-postgres-data:

networks:
  web2lab1-network:
    driver: bridge
